const transactions = [
  {
    id: "12345",
    date: "2022-04-01T10:00:00Z",
    description: "Salary",
    amount: 5000.0,
    category: "Income",
    location: "San Francisco, CA",
    payment_method: "Direct deposit",
    status: "Completed",
    notes: "Monthly paycheck from ABC Inc.",
  },
  {
    id: "67890",
    date: "2022-04-03T14:30:00Z",
    description: "Groceries",
    amount: -85.25,
    category: "Food & Drink",
    location: "San Francisco, CA",
    merchant: "Safeway",
    payment_method: "Visa ****1234",
    status: "Completed",
    notes: "Bought groceries for the week",
  },
  {
    id: "23456",
    date: "2022-04-05T09:00:00Z",
    description: "Electric bill",
    amount: -100.0,
    category: "Utilities",
    location: "San Francisco, CA",
    merchant: "Pacific Gas & Electric",
    payment_method: "Visa ****5678",
    status: "Completed",
    notes: "",
  },
  {
    id: "78901",
    date: "2022-04-07T13:15:00Z",
    description: "Lunch with colleagues",
    amount: -40.0,
    category: "Food & Drink",
    location: "San Francisco, CA",
    merchant: "The Cheesecake Factory",
    payment_method: "Visa ****9012",
    status: "Completed",
    notes: "Had lunch with colleagues at the Cheesecake Factory",
  },
  {
    id: "34567",
    date: "2022-04-10T18:00:00Z",
    description: "Netflix subscription",
    amount: -15.99,
    category: "Entertainment",
    location: "San Francisco, CA",
    merchant: "Netflix",
    payment_method: "Visa ****3456",
    status: "Completed",
    notes: "Monthly subscription fee for Netflix",
  },
  {
    id: "89012",
    date: "2022-04-12T11:30:00Z",
    description: "Gasoline",
    amount: -35.0,
    category: "Transportation",
    location: "San Francisco, CA",
    merchant: "Shell",
    payment_method: "Visa ****7890",
    status: "Completed",
    notes: "Filled up the car with gasoline",
  },
  {
    id: "45678",
    date: "2022-04-14T09:00:00Z",
    description: "Internet bill",
    amount: -80.0,
    category: "Utilities",
    location: "San Francisco, CA",
    merchant: "Comcast",
    payment_method: "Visa ****2345",
    status: "Completed",
    notes: "",
  },
  {
    id: "90123",
    date: "2022-04-16T12:30:00Z",
    description: "Brunch with friends",
    amount: -60.0,
    category: "Food & Drink",
    location: "San Francisco, CA",
    merchant: "The Grove",
    payment_method: "Visa ****6789",
    status: "Completed",
    notes: "Had brunch with friends",
  },
  {
    id: "56789",
    date: "2022-04-18T15:00:00Z",
    description: "Haircut",
    amount: -50.0,
    category: "Personal Care",
    location: "San Francisco, CA",
    merchant: "Supercuts",
    payment_method: "Visa ****1234",
    status: "Completed",
    notes: "Got a haircut at Supercuts",
  },
  {
    id: "12346",
    date: "2022-04-20T20:00:00Z",
    description: "Dinner date",
    amount: -100.00,
    category: "Food & Drink",
    location: "San Francisco, CA",
    merchant: "Morton's Steakhouse",
    payment_method: "Visa ****5678",
    status: "Completed",
    notes: "Went on a dinner date with my partner"
  },
  {
    id: "67891",
    date: "2022-04-22T16:30:00Z",
    description: "Gasoline",
    amount: -40.00,
    category: "Transportation",
    location: "San Francisco, CA",
    merchant: "Chevron",
    payment_method: "Visa ****9012",
    status: "Completed",
    notes: "Filled up the car with gasoline"
  },
  {
    id: "23457",
    date: "2022-04-24T14:00:00Z",
    description: "Concert tickets",
    amount: -200.00,
    category: "Entertainment",
    location: "San Francisco, CA",
    merchant: "Ticketmaster",
    payment_method: "Visa ****3456",
    status: "Completed",
    notes: "Bought tickets to see my favorite band"
  },
  {
    id: "78902",
    date: "2022-04-26T11:00:00Z",
    description: "Medical bill",
    amount: -150.00,
    category: "Healthcare",
    location: "San Francisco, CA",
    merchant: "Kaiser Permanente",
    payment_method: "Visa ****7890",
    status: "Completed",
    notes: "Paid medical bill for recent doctor visit"
  },
  {
    id: "34568",
    date: "2022-04-28T08:00:00Z",
    description: "Rent",
    amount: -2500.00,
    category: "Housing",
    location: "San Francisco, CA",
    merchant: "ABC Apartments",
    payment_method: "Visa ****2345",
    status: "Completed",
    notes: "Paid monthly rent"
  },
  {
    id: "89013",
    date: "2022-04-30T10:00:00Z",
    description: "Amazon purchase",
    amount: -75.00,
    category: "Shopping",
    location: "Online",
    merchant: "Amazon",
    payment_method: "Visa ****6789",
    status: "Completed",
    notes: "Bought a new book and some household items on Amazon"
  }
];

export default transactions;